spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/soa-1
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




